### ISSUE TITLE
pause and resume downloads feature?

### ISSUE THREAD

**Issue by overflowz** [rosshinkley/nightmare-download-manager#11]
Hi. I'd like to have pause and resume downloads for certain things.

Let's say, I'd like to download multiple files, but I want to know the progress of whole files.
Files are less than 1kb (or equal) and they're like 100+.

I want to add download items in paused state and start downloading all of them together, so I will know the overall progress of them.

**Comment by rosshinkley** [comment]
You _could_ conceivably do this now, but it'd be a mess trying to manage the event modeling with `.on('download')`.

If you know how many files there are up front, why not use `.on('download')` and track it yourself?

As a compromise, what about having a download status that returns back an object that has, say, files finished, files requested, and maybe total data volume transfered?  Would that get close to something useful for you?

**Comment by overflowz** [comment]
I managed it in a different way. Have a look:

```
function getActiveDownloadsCount(nightmare: any) {
  let numActiveDownloads = 0;

  if (nightmare._downloads) {
    numActiveDownloads =
      Object.keys(nightmare._downloads)
        .map(key => nightmare._downloads[key])
        .filter(item => item.state !== 'completed' && item.state !== 'interrupted' && item.state !== 'cancelled')
        .length;
  }

  return numActiveDownloads;
}
...
if (state === 'completed') {
          const totalDownloadsCount: number = Object.keys(nightmare._downloads).length;

          // future downloads may delay downloading so we delay it too.
          if (!getActiveDownloadsCount(nightmare)) {
            setTimeout(async function (count) {
              if (Object.keys(nightmare._downloads).length === count) {
                // actual complete here
              }
            }.bind(this, totalDownloadsCount), 5000);
          }
        }
```
