### ISSUE TITLE
original URI get's lost in redirect.

### ISSUE THREAD

**Issue by rmoriz** [rosshinkley/nightmare-download-manager#4]
Hi,

given the following download scenario:
- the original href contains important information, e.g. transaction number
- on `click()` nightmare is redirected to another URL which dynamically creates the asset that get's downloaded
- `downloadItem` in the callback shows only the last URL but not the pre-redirect path. The information is lost.
- there is afaik no way to "synchronize" it outside of nightmare-download-manager

**Comment by rosshinkley** [comment]
Hm, the URL is derived from the event that starts the download - I would _think_ it's the dynamic address in your example (and I'm surprised it isn't).  I will spend some time with the Electron documentation to see if I'm missing something, but this may end up being a limitation.

**Comment by rmoriz** [comment]
My example is the invoice download at Amazon.de (probably amazon.com, too).

The href on the overview page contains something like `/static/download?orderID=######&sign_key=XXXXX"

This returns a redirect to S3, e.g. `s3.amazonaws.com/invoices/random-generated-hash-id.pdf?expires=DATE`

`downloadItem` only contains the s3 link (which is unfortunately also the filename sent), the original pre-redirect address is lost. Because the random-hash changes all time, I can't match the downloadItem to the original orderID

**Comment by rosshinkley** [comment]
Ah, I see.  I had it backwards, I thought you were saying the the `href` address was the one being returned from the download item, not the S3 address.

I think I'm following your problem now.  You want the download event causing URL to be in the download item so you can match up records.  That's... not going to be easy.  Downloads can be triggered by many things, the redirect chain can be arbitrarily deep, and if you trigger more than one download, you're no longer guaranteed order.

The easiest thing to do would be to use `nightmare-inline-download` and perform these downloads in series so you have a guaranteed order.  (I realize this is also the slowest option.)  You might also want to take a look at the headers S3 returns, there may be more information there.  You _could_ also scrape the PDF to figure out the orderID, but that would likely be very, very fragile.

**Comment by rmoriz** [comment]
S3 does not provide any useful headers, scraping the PDF sadly does not work, because amazon uses different templates for different products (seems to be a regional speciality for same-day-delivery things).

Looks like `nightmare-inline-download` seems to be the best solution, I'll look into it and give it a try. That said I'm not familiar with all the different "Promises" solutions so I can loop over all `href` values that I've extracted using the `.evaluate()` function. Well, let's see…

Thanks :-)

**Comment by rosshinkley** [comment]
No problem!  Happy to try and help.

I know `nightmare-inline-download` has an issue (that I think you reported?) having to do with the Electron upgrade to 1.x, I'm planning on digging into that shortly.

I don't know if you've seen it yet or if it would be helpful, but a while back I started working on [`nightmare-examples`](https://github.com/rosshinkley/nightmare-examples), and specifically, the section on [asynchronous operations and loops](https://github.com/rosshinkley/nightmare-examples/blob/master/docs/common-pitfalls/async-operations-loops.md) might be of interest.

**Comment by rmoriz** [comment]
Yes, iirc I had the issue with `nightmare-download-manager` as well. I've downgraded my `nightmare` to the version you specified in the `package.json` file so this works for now (with the old nightmare version).

I'll definitly look into the examples. thanks :-)

**Comment by rosshinkley** [comment]
Closing this for now.  May possibly revisit.
